let stockProductos = [
    {id: 1, nombre: "Esporas 1", tipo: "esporas", cantidad: 1, desc: "Esporas X 200ml", precio: 1200, categoria: "3", img: './img/spore_png.png'},
    {id: 2, nombre: "Esporas 2", tipo: "esporas", cantidad: 1, desc: "Esporas X 100ml", precio: 1100, categoria: "2", img: './img/spore_png.png'},
    {id: 3, nombre: "Esporas 3", tipo: "esporas", cantidad: 1, desc: "Esporas X 300ml", precio: 1200, categoria: "1", img: './img/spore_png.png'},
    {id: 4, nombre: "Esporas 4", tipo: "esporas", cantidad: 1, desc: "Esporas X 400ml", precio: 1400, categoria: "3", img: './img/spore_png.png'},
    {id: 5, nombre: "Esporas 5", tipo: "esporas", cantidad: 1, desc: "Esporas X 500ml", precio: 1200, categoria: "2", img: './img/spore_png.png'},
    {id: 6, nombre: "Esporas 6", tipo: "esporas", cantidad: 1, desc: "Esporas X 1600ml", precio: 1500, categoria: "1", img: './img/spore_png.png'},
    {id: 7, nombre: "Kit de Cultivo 1", tipo: "kit", cantidad: 1, desc: "Kit de Cultivo 1", precio: 500, categoria: "3", img: './img/KIT_CULTIVO.webp'},
    {id: 8, nombre: "Kit de Cultivo 2", tipo: "kit", cantidad: 1, desc: "Kit de Cultivo 2", precio: 500, categoria: "2", img: './img/KIT_CULTIVO.webp'},
    {id: 9, nombre: "Kit de Cultivo 3", tipo: "kit", cantidad: 1, desc: "Kit de Cultivo 3", precio: 500, categoria: "1", img: './img/KIT_CULTIVO.webp'},
    {id: 10, nombre: "Kit de Cultivo 4", tipo: "kit", cantidad: 1, desc: "Kit de Cultivo 4", precio: 700, categoria: "3", img: './img/KIT_CULTIVO.webp'},
    {id: 11, nombre: "Kit de Cultivo 5", tipo: "kit", cantidad: 1,desc: "Kit de Cultivo 5", precio: 700, categoria: "2", img: './img/KIT_CULTIVO.webp'},
    {id: 12, nombre: "Kit de Cultivo 6", tipo: "kit", cantidad: 1, desc: "Kit de Cultivo 6", precio: 700, categoria: "1", img: './img/KIT_CULTIVO.webp'},
    {id: 13, nombre: "Micelio 1", tipo: "micelio", cantidad: 1, desc: "Micelio 1 x 200ml", precio: 900, categoria: "3", img: './img/micelio.webp'},
    {id: 14, nombre: "Micelio 2", tipo: "micelio", cantidad: 1, desc: "Micelio 2 x 400ml", precio: 1400, categoria: "2", img: './img/micelio.webp'},
    {id: 15, nombre: "Micelio 3", tipo: "micelio", cantidad: 1, desc: "Micelio 3 x 600ml", precio: 7000, categoria: "1", img: './img/micelio.webp'},
    {id: 16, nombre: "Micelio 4", tipo: "micelio", cantidad: 1, desc: "Micelio 4 x 800ml", precio: 777, categoria: "3", img: './img/micelio.webp'},
    {id: 17, nombre: "Micelio 5", tipo: "micelio", cantidad: 1, desc: "Micelio 5 x 1L", precio: 234, categoria: "2", img: './img/micelio.webp'},
    {id: 18, nombre: "Micelio 6", tipo: "micelio", cantidad: 1, desc: "Micelio 6 x 50L", precio: 155600, categoria: "1", img: './img/micelio.webp'},
    {id: 19, nombre: "Tratamiento 1", tipo: "tratamiento", cantidad: 1, desc: "Tratamiento microdosis x 100 comprimidos", precio: 1600, categoria: "3", img: './img/tratamiento.jpg'},
    {id: 20, nombre: "Tratamiento 2", tipo: "tratamiento", cantidad: 1, desc: "Tratamiento microdosis x 200 comprimidos", precio: 3200, categoria: "2", img: './img/tratamiento.jpg'},
    {id: 21, nombre: "Tratamiento 3", tipo: "tratamiento", cantidad: 1, desc: "Tratamiento microdosis x 400 comprimidos", precio: 2300, categoria: "1", img: './img/tratamiento.jpg'},
    {id: 22, nombre: "Tratamiento 4", tipo: "tratamiento", cantidad: 1, desc: "Tratamiento microdosis x 600 comprimidos", precio: 5600, categoria: "3", img: './img/tratamiento.jpg'},
    {id: 23, nombre: "Tratamiento 5", tipo: "tratamiento", cantidad: 1, desc: "Tratamiento microdosis x 800 comprimidos", precio: 1700, categoria: "2", img: './img/tratamiento.jpg'},
    {id: 24, nombre: "Tratamiento 6", tipo: "tratamiento", cantidad: 1, desc: "Tratamiento microdosis x 50 comprimidos", precio: 800, categoria: "1", img: './img/tratamiento.jpg'},
]